import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.4.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-04",
        enabledModels: [
          "shopifyApp",
          "shopifyAppCredit",
          "shopifyAppInstallation",
          "shopifyAppPurchaseOneTime",
          "shopifyAppSubscription",
          "shopifyAppUsageRecord",
          "shopifyBusinessEntity",
          "shopifyDomain",
          "shopifyOrder",
        ],
        type: "partner",
        scopes: [
          "write_checkouts",
          "read_checkouts",
          "write_customers",
          "read_customers",
          "write_orders",
          "read_orders",
          "write_products",
          "read_products",
          "write_app_proxy",
          "write_cart_transforms",
          "read_cart_transforms",
          "write_companies",
          "read_companies",
          "write_customer_merge",
          "read_customer_merge",
          "write_content",
          "read_content",
          "write_checkout_branding_settings",
          "read_checkout_branding_settings",
          "read_fulfillments",
          "write_files",
          "read_files",
          "write_draft_orders",
          "read_draft_orders",
          "unauthenticated_write_checkouts",
          "unauthenticated_read_checkouts",
          "unauthenticated_write_customers",
          "unauthenticated_read_customers",
          "unauthenticated_read_product_listings",
          "unauthenticated_read_product_inventory",
          "unauthenticated_read_metaobjects",
          "unauthenticated_read_customer_tags",
          "unauthenticated_read_content",
          "unauthenticated_read_product_tags",
          "unauthenticated_read_product_pickup_locations",
          "unauthenticated_read_selling_plans",
          "write_themes",
          "read_themes",
          "write_translations",
          "read_translations",
          "write_inventory",
          "read_inventory",
          "write_locales",
          "read_locales",
          "write_locations",
          "read_locations",
          "write_marketing_events",
          "read_marketing_events",
          "write_markets",
          "read_markets",
          "write_merchant_managed_fulfillment_orders",
          "read_merchant_managed_fulfillment_orders",
          "write_metaobject_definitions",
          "read_metaobject_definitions",
          "write_metaobjects",
          "read_metaobjects",
          "write_online_store_navigation",
          "read_online_store_navigation",
          "write_order_edits",
          "read_order_edits",
          "write_payment_customizations",
          "read_payment_customizations",
          "write_pixels",
          "write_privacy_settings",
          "read_privacy_settings",
          "read_product_listings",
          "write_script_tags",
          "read_script_tags",
        ],
      },
    },
  },
};
